name: Run Test

on:
    push:
        branches:
            - '*'

jobs:
    laravel-tests:
        runs-on: ubuntu-latest
        container:
            image: kirschbaumdevelopment/laravel-test-runner:8.1

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v3

            -   name: Install Dependencies
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

            -   name: Generate App Key
                run: php artisan key:generate

            -   name: Execute tests
                run: vendor/bin/phpunit